name: Tag Repository

on:
  push:
    branches:
      - main
      - feat/devops

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gitpython

      - name: Determine Version Type
        id: version_type
        run: |
          if [[ $GITHUB_REF == refs/heads/main ]]; then
            echo "VERSION_TYPE=minor" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == refs/heads/feat/devops ]]; then
            echo "VERSION_TYPE=patch" >> $GITHUB_ENV
          else
            echo "VERSION_TYPE=patch" >> $GITHUB_ENV
          
      - name: Tag Repository
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python tag_repo.py ${{ env.VERSION_TYPE }}
