name: Tag and Release

on:
  push:
    branches:
      - main
      - feat/devops

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    # - name: Checkout code
    #   uses: actions/checkout@v4

    # - name: Set up Python
    #   uses: actions/setup-python@v5
    #   with:
    #     python-version: '3.10'

    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install gitpython

    # - name: Determine version type
    #   id: get-version-type
    #   run: |
    #     if [[ $GITHUB_REF == refs/heads/main ]]; then
    #       echo "::set-output name=version_type::minor"
    #     elif [[ $GITHUB_REF == refs/heads/feat/devops ]]; then
    #       echo "::set-output name=version_type::patch"
    #     else
    #       echo "::set-output name=version_type::patch"
    #     fi

    # - name: Tag the repo
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    #     GITHUB_REPOSITORY: ${{ github.repository }}
    #   run: |
    #     python tag_repo.py ${{ steps.get-version-type.outputs.version_type }}

    - uses: actions/checkout@v4
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GH_TOKEN }}
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }} 